package org.mediaecosystem.experimental.platformproof.model;

public enum ProofState {
    NEVER_SELECTED,
    PERMISSION_GRANTED,
    ACCESSIBLE,
    PROCESS_RESTARTED_AND_STILL_ACCESSIBLE,
    REBOOTED_AND_STILL_ACCESSIBLE,
    TEMPORARILY_UNAVAILABLE,
    PERMISSION_REVOKED,
    VOLUME_REINSERTED,
    EXPLICIT_RELINK_REQUIRED,
    EXPLICIT_RELINK_SUCCEEDED,
    CLEANUP_COMPLETE
}
