package org.mediaecosystem.experimental.platformproof.model;

public enum StorageEvent {
    SELECT_WITH_PERMISSION,
    ACCESS_CONFIRMED,
    PROCESS_RELAUNCH_CONFIRMED,
    REBOOT_RELAUNCH_CONFIRMED,
    ACCESS_UNAVAILABLE,
    GRANT_REVOKED,
    ACCESS_RESTORED,
    RELINK_REQUIRED,
    EXPLICIT_RELINK_VALIDATED,
    CLEANUP_VALIDATED_AND_COMPLETE
}
